version : '3'

services :
    ngx :
      build:
        context : Nginx/
        dockerfile : Dockerfile
      ports : 
        - "443:443"
      container_name : nginx
      volumes : 
          - ./db:/var/www/html/aelandal_db
      networks :
          - link
    wp :
      build : 
        context : Wordpress/
        dockerfile : Dockerfile
      container_name : wordpress
      volumes :
          - ./db:/var/www/html/aelandal_db
      networks :
          - link
networks :
  link : 
    driver: "bridge" 

