version : '3.7'

services :
    nginx :
      build:
        context : requirements/Nginx/
        dockerfile : Dockerfile
      ports : 
        - "443:443"
      container_name : nginx
      env_file : .env
      restart : always
      volumes : 
          - /home/aelandal/data/wordpress:/var/www/html/wordpress
      depends_on:
        - wordpress
      networks :
          - link
    wordpress :
      build : 
        context : requirements/Wordpress/
        dockerfile : Dockerfile
#      environment:
#        WP_DB_NAME: ${WP_DB_NAME}
#        WP_USER_NAME: ${WP_USER_NAME}
#        WP_USE_PASSWD: ${WP_USE_PASSWD}
#        WP_DB_HOST: ${WP_DB_HOST}

      container_name : wordpress
      env_file : .env
      restart : always
      ports:
        - "9000:9000"
      volumes :
          - /home/aelandal/data/wordpress:/var/www/html/wordpress
      networks :
          - link
      depends_on:
        - mariadb
    mariadb :
      build : 
        context : requirements/Mariadb/
        dockerfile : Dockerfile
      container_name : mariab
      env_file : .env
      restart : always
      volumes :
        - /home/aelandal/data/mariadb:/var/lib/mysql
      networks :
        - link
          #  depends_on:
          #- wordpress



networks :
  link:
    name: link
    driver: "bridge" 

